name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main   # Hugo 源码所在分支，改成你实际的分支名

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@main

      - name: Setup Hugo
        uses: jakejarvis/hugo-build-action@master
        with:
          args: --minify --buildDrafts   # 或者指定版本，比如 '0.134.2'

      - name: Build site
        run: hugo --minify

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
