# This is a basic workflow to help you get started with Actions

name: Deploy to aliyun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Build Hugo
        uses: lowply/build-hugo@v0.92.1

     # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }} # 云服务器私钥
          ARGS: "-avzr --delete --exclude /.user.ini" # 忽略服务器上的.user.ini文件
          SOURCE: "public/" # hexo编译之后的博客文件目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # 云服务器ip地址
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # 云服务器用户名
          TARGET: ${{ secrets.TARGET }} # 部署的云服务器目录
